# Generated by Django 3.2 on 2021-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'Admin'), (2, 'Staff'), (3, 'Merchant'), (4, 'Customer')], default=1, max_length=225),
        ),
    ]
